### ISSUE TITLE
Missing attributes in cidaas_app in v3.0.0/3.0.1

### ISSUE THREAD

**Issue by joschug** [Cidaas/terraform-provider-cidaas#17]
Little regression in 3.0.0: The state of `cidaas_app` doesn't seem to include empty mandatory fields `redirect_urls` and `allowed_logout_urls`.

They're not included when showing state with `tofu state show`. After adding and applying them, they'll keep being shown as unapplied changes.

And while `cidaas_user_groups` can now be created just fine, the group keeps showing up as changed (with no visible change) even though state and config appear to be identical.

Tested with 3.0.1 also, still applies.

**Comment by joschug** [comment]
Tujit, thank you for looking into the issues. Today I tried v3.0.2 and it solves the issue regarding empty `allowed_logout_urls`. 

Empty `redirect_uris` still show up as unapplied changes, same with the `cidaas_user_groups`.

**Comment by tujit** [comment]
Hi @joschug , we have released the version [3.0.3](https://registry.terraform.io/providers/Cidaas/cidaas/3.0.3) with the required changes. Please try the new build and let us know if it resolves your issues.

We appreciate your patience and thank you for your continued support!

**Comment by tujit** [comment]
Since we haven’t heard back we’re closing this issue. If you encounter any other issue, please let us know by opening a new one.
